# Generated by Django 5.2.13 on 2026-04-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking_app.parkinglot'),
        ),
    ]
