# Generated by Django 5.2.13 on 2026-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_parkingsession_parking_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpass',
            name='pass_type',
            field=models.CharField(choices=[('drop-off', 'Drop-Off'), ('park', 'Park')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='pass_type',
            field=models.CharField(choices=[('drop-off', 'Drop-Off'), ('park', 'Park')], max_length=20),
        ),
    ]
