# Generated by Django 5.2.13 on 2026-04-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_alter_parkingpass_pass_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
