# Generated by Django 4.2.11 on 2026-04-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
