# Generated by Django 4.2.11 on 2026-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0009_alter_vehicle_is_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_registered',
        ),
    ]
