# Generated by Django 4.2.11 on 2026-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0010_remove_vehicle_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pass_type',
            field=models.CharField(choices=[('park', 'Parking'), ('drop_off', 'Drop-off')], default='park', max_length=10),
        ),
    ]
